-- Section1
SELECT ACCOUNT_NO
FROM accounts
GROUP BY ACCOUNT_NO
ORDER BY COUNT(*) DESC;
-- Section2
SELECT YEAR(DATE) AS 'YEAR(DATE)', date AS 'DATE'
FROM accounts
GROUP BY DATE
HAVING count(*) > 10
ORDER BY count(DATE) DESC;
-- Section3
SELECT A.ACCOUNT_NO, MIN(BALANCE) AS BALANCE
FROM accounts A,
     (SELECT ACCOUNT_NO, MAX(DATE) AS MAX_DATE
      FROM accounts
      GROUP BY ACCOUNT_NO) B
WHERE A.ACCOUNT_NO = B.ACCOUNT_NO
  AND A.DATE = B.MAX_DATE
  AND A.BALANCE < -1000000000
GROUP BY ACCOUNT_NO
ORDER BY BALANCE;
-- Section4
START TRANSACTION;

UPDATE accounts
SET BALANCE = BALANCE - 1000000
WHERE ACCOUNT_NO = 45532;

UPDATE accounts
SET BALANCE = BALANCE + 1000000
WHERE ACCOUNT_NO = 32124;
COMMIT;




